const BAD_DOMAINS = new Set(['google.com','bing.com','yahoo.com','yelp.com','zillow.com','realtor.com','homes.com','loopnet.com','yellowpages.com','facebook.com','instagram.com','linkedin.com','tripadvisor.com','opentable.com','wikipedia.org','photon.komoot.io','nominatim.openstreetmap.org','openstreetmap.org']);
const clean=(v,n=3000)=>v==null?'':String(v).trim().slice(0,n);
const first=(...xs)=>{for(const x of xs){const s=clean(x,1200);if(s)return s}return ''};
const uniq=a=>[...new Set((a||[]).filter(Boolean).map(x=>clean(x,500)))];
function urlOf(v){try{const u=new URL(String(v).trim());if(!/^https?:$/.test(u.protocol))return '';u.hash='';return u.href}catch{return ''}}
function domain(v){try{return new URL(v).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}}
function valid(v){const u=urlOf(v),d=domain(u);return u&&d&&!([...BAD_DOMAINS].some(x=>d===x||d.endsWith('.'+x)))?u:''}
function stripHtml(s){return String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function jsonLd(html){const out=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))){try{const v=JSON.parse(m[1]);const add=x=>{if(!x)return;if(Array.isArray(x))x.forEach(add);else if(x['@graph'])add(x['@graph']);else out.push(x)};add(v)}catch{}}return out}
function inspect(html,text,site){const raw=String(html||''),body=clean(text||stripHtml(raw),30000),low=body.toLowerCase(),ld={};for(const x of jsonLd(raw)){const types=Array.isArray(x['@type'])?x['@type']:[x['@type']];if(types.some(v=>/Organization|LocalBusiness|RealEstateAgent|ProfessionalService|Restaurant|Hotel|Dentist/i.test(String(v))))Object.assign(ld,x)}
 const title=first((raw.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||[])[1]);
 const description=first((raw.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)||[])[1],(raw.match(/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i)||[])[1]);
 const emails=uniq([...(body.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig)||[]),...((raw.match(/mailto:([^"'?]+)/ig)||[]).map(x=>x.slice(7)))]);
 const phones=uniq([...(body.match(/(?:\+?\d[\d\s().-]{7,}\d)/g)||[]),...((raw.match(/tel:([^"'?]+)/ig)||[]).map(x=>x.slice(4)))]);
 const socials=[];const sr=/href=["'](https?:\/\/(?:www\.)?(?:facebook|instagram|linkedin|youtube|x|twitter|tiktok)\.com[^"' ]*)/ig;let sm;while((sm=sr.exec(raw)))socials.push(urlOf(sm[1]));
 const same=Array.isArray(ld.sameAs)?ld.sameAs:[ld.sameAs];socials.push(...same.map(valid).filter(Boolean));
 const address=ld.address&&typeof ld.address==='object'?[ld.address.streetAddress,ld.address.addressLocality,ld.address.addressRegion,ld.address.postalCode].filter(Boolean).join(', '):'';
 const serviceWords=['buy','sell','rent','leasing','property management','investment','relocation','luxury','commercial','residential','consultation','valuation','brokerage','mortgage','financing','booking','appointment','catering','delivery','repair','installation','membership','training','treatment','legal','accounting'];
 const services=uniq(serviceWords.filter(w=>low.includes(w)).map(w=>w.replace(/\b\w/g,c=>c.toUpperCase())));
 const signals={hasForm:/<form\b/i.test(raw)||/contact form|request (a )?quote|send (a )?message/i.test(body),hasCTA:/(book|schedule|request|contact|consultation|get started|call us|enquire|inquire|appointment|valuation|talk to)/i.test(low),hasChat:/(intercom|drift|tidio|zendesk|crisp|livechat|tawk\.to|chatbot|ai assistant|virtual assistant)/i.test(low),hasQualification:/(budget|price range|timeline|requirements|property type|preferred|when are you looking|how can we help|tell us about)/i.test(low),hasAnalytics:/(google tag manager|google analytics|facebook pixel|meta pixel|hotjar|clarity)/i.test(low),rating:first(ld.aggregateRating?.ratingValue,ld.ratingValue)};
 return {url:site,title:clean(title,500),description:clean(description,1200),name:first(ld.name),address,phone:first(ld.telephone,phones[0]),phones,email:first(ld.email,emails[0]),emails,socials:uniq(socials),services,signals,headings:uniq([...raw.matchAll(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/gi)].map(m=>stripHtml(m[1]))).slice(0,12),contentLength:body.length};
}
async function inspectSite(site){const u=valid(site);if(!u)return null;let html='',text='';try{const r=await fetch(u,{redirect:'follow',headers:{accept:'text/html,application/xhtml+xml','user-agent':'Mozilla/5.0 LeadFlowProspectResearch/6.0'}});if(r.ok)html=await r.text()}catch{}try{const r=await fetch('https://r.jina.ai/'+u,{headers:{accept:'text/plain','user-agent':'LeadFlowProspectResearch/6.0'}});if(r.ok)text=await r.text()}catch{}if(!html&&!text)return null;return inspect(html,text,u)}
async function officialSearch(name,location,industry){const q=`"${name}" "${location}" ${industry} official website`;try{const r=await fetch('https://html.duckduckgo.com/html/?q='+encodeURIComponent(q),{headers:{accept:'text/html','user-agent':'Mozilla/5.0 LeadFlowProspectResearch/6.0'}});if(!r.ok)return '';const h=await r.text(),urls=[];const re=/<a[^>]+class=["'][^"']*result__a[^"']*["'][^>]+href=["']([^"']+)["'][^>]*>/gi;let m;while((m=re.exec(h))&&urls.length<12){let href=m[1];try{if(href.includes('uddg='))href=decodeURIComponent(new URL(href,'https://html.duckduckgo.com').searchParams.get('uddg')||'')}catch{}const u=valid(href);if(u&&!urls.some(x=>domain(x)===domain(u)))urls.push(u)}const words=clean(name,200).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2&&!['the','and','inc','llc','ltd','real','estate','company','group'].includes(x));return urls.map(u=>({u,s:words.reduce((n,w)=>n+(domain(u).includes(w)?10:0),0)})).sort((a,b)=>b.s-a.s)[0]?.u||''}catch{return ''}}
function decodeResultUrl(href){try{if(href.includes('uddg='))return decodeURIComponent(new URL(href,'https://html.duckduckgo.com').searchParams.get('uddg')||'')}catch{}return href}
function searchContactValues(html,name){const tokens=clean(name,200).toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2&&!['the','and','inc','llc','ltd','real','estate','company','group','international'].includes(x));const emailRe=/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig,phoneRe=/(?:\+?\d[\d\s().-]{7,}\d)/g;const hits=[],patterns=[/<a[^>]+class=["'][^"']*result__a[^"']*["'][^>]+href=["']([^"']+)["'][^>]*>/gi,/<a[^>]+href=["']([^"']+)["'][^>]+class=["'][^"']*result__a[^"']*["'][^>]*>/gi];for(const re of patterns){let m;while((m=re.exec(html))){const u=valid(decodeResultUrl(m[1]));if(!u||hits.some(x=>x.url===u))continue;const chunk=stripHtml(html.slice(m.index,m.index+7000));const low=chunk.toLowerCase();const overlap=tokens.reduce((n,t)=>n+(low.includes(t)?1:0),0);const emails=uniq(chunk.match(emailRe)||[]).filter(e=>!/@(?:example|sentry|schema|wix|wordpress)\./i.test(e));const phones=uniq(chunk.match(phoneRe)||[]);if((emails.length||phones.length)&&overlap>0)hits.push({url:u,emails,phones,score:overlap*10+(emails.length?4:0)+(phones.length?2:0)})}}return hits.sort((a,b)=>b.score-a.score)}
async function publicContactSearch(name,location,industry){if(!name)return null;const queries=[`"${name}" "${location}" ${industry} email phone`,`"${name}" "${location}" email`,`"${name}" "${location}" phone`];const hits=[];for(const q of queries){try{const r=await fetch('https://html.duckduckgo.com/html/?q='+encodeURIComponent(q),{headers:{accept:'text/html','user-agent':'Mozilla/5.0 LeadFlowProspectResearch/6.0'}});if(!r.ok)continue;const h=await r.text();hits.push(...searchContactValues(h,name))}catch{}}const best={emails:[],phones:[],sources:[]};for(const h of hits.sort((a,b)=>b.score-a.score).slice(0,8)){best.emails.push(...h.emails);best.phones.push(...h.phones);if(h.url)best.sources.push(h.url);if(best.emails.length&&best.phones.length)break}best.emails=uniq(best.emails);best.phones=uniq(best.phones);best.sources=uniq(best.sources);return best.emails.length||best.phones.length?best:null}
async function mapLimit(items,n,fn){const out=new Array(items.length);let i=0;await Promise.all(Array.from({length:Math.min(n,items.length)},async()=>{while(true){const k=i++;if(k>=items.length)return;try{out[k]=await fn(items[k],k)}catch{out[k]=null}}}));return out}
export async function researchProspects(prospects,{location='',industry=''}={}){const items=Array.isArray(prospects)?prospects.slice(0,100):[];return mapLimit(items,5,async p=>{let site=valid(p.website),found=false;if(!site&&p.name){site=await officialSearch(p.name,location,industry);found=!!site}const s=site?await inspectSite(site):null;const publicContacts=await publicContactSearch(p.name,location,industry);const phones=uniq([p.phone,s?.phone,...(s?.phones||[]),...(publicContacts?.phones||[])]);const emails=uniq([p.email,s?.email,...(s?.emails||[]),...(publicContacts?.emails||[])]);const final={...p,website:s?.url||site||'',phone:first(p.phone,s?.phone,phones[0]),email:first(p.email,s?.email,emails[0]),socials:uniq([...(p.socials||[]),...(s?.socials||[])])};const r=s?{status:'inspected',title:s.title,description:s.description,address:s.address||p.address||'',phones,emails,socials:uniq(final.socials),services:s.services,headings:s.headings,contentLength:s.contentLength,signals:s.signals,contactSources:uniq(publicContacts?.sources||[]),evidence:[s.signals.hasForm?'Lead form detected':'No obvious lead form detected',s.signals.hasCTA?'Conversion CTA detected':'No strong conversion CTA detected',s.signals.hasChat?'Chat/AI signal detected':'No obvious AI/live-chat signal detected',s.signals.hasQualification?'Qualification questions detected':'No obvious qualification questions detected',s.signals.hasAnalytics?'Analytics/measurement signal detected':'No obvious analytics signal detected',emails.length?'Public email contact found':'No public email contact found',phones.length?'Public phone contact found':'No public phone contact found']}:{status:site?'website-found':'public-record-only',title:'',description:'',address:p.address||'',phones,emails,socials:final.socials,services:[],headings:[],contentLength:0,signals:{},contactSources:uniq(publicContacts?.sources||[]),evidence:[site?'Website found but could not be inspected':'No verified official website found',emails.length?'Public email contact found':'No public email contact found',phones.length?'Public phone contact found':'No public phone contact found']};return {...final,websiteFoundBySearch:found,research:r};})}