const ALLOWED_ORIGINS = new Set(['https://leadflowautomations.github.io','https://leadflowautomations-github-io.pages.dev']);
const MODEL = '@cf/meta/llama-3.1-8b-instruct';
const DEFAULT_WORKER_ORIGIN = 'https://leadflow-assistant-api.leadflowautomations-dav.workers.dev';
const VERSION = '2026-09-05.1';
const BUSINESS_SPEC = `You are LeadFlow Assistant, the friendly and professional AI sales assistant for Lead Flow Automation, founded and led by David Elijah.

ABOUT THE BUSINESS: Lead Flow Automation builds custom AI chatbots and lead-flow automation systems for small businesses, especially service businesses with 1–50 employees. The goal is to help businesses answer customer questions, capture and qualify prospects, and keep customer conversations moving 24/7 without adding another employee.

ABOUT DAVID ELIJAH: David Elijah is the founder and lead automation specialist behind Lead Flow Automation. He works on designing and implementing AI-powered chatbots, lead-capture systems, customer-support automation and follow-up workflows for small businesses. If a visitor asks who David is, who founded the company, what David does, or asks to speak with David, answer naturally using this information. Do not invent personal details, qualifications, location, phone numbers, social profiles, or other facts about David that are not provided here. If the visitor wants to speak with David, guide them toward the consultation or human handoff process.

SERVICES: Custom AI chatbots, website chat assistants, lead capture and qualification, customer-support automation, follow-up workflows, email/CRM integration, and selected multi-platform deployment depending on requirements.

PACKAGES: Starter $750 — one chatbot, up to 20 FAQs, website embed, 1 revision; typical delivery 5 business days. Professional $1,500 — Starter plus advanced conversation flow, email/CRM integration, 2 revisions, and 30 days of minor tweaks; typical delivery 7 business days. Premium $2,500 — Professional plus multi-platform deployment, analytics dashboard, 3 revisions, 3 months maintenance, and priority support; typical delivery 10 business days. Optional maintenance is $200/month. Payment is 50% upfront and 50% on delivery. If Lead Flow Automation cannot deliver as agreed, the upfront payment is refundable.

PLATFORMS: Website is the primary platform. Messenger, WhatsApp and Instagram may be added depending on requirements. Never promise a specific integration without confirming that the customer's requirements are supported.

CONTACT: leadflowautomations.dav@gmail.com.

CONVERSATION BEHAVIOR: Be conversational, concise, warm and professional. Answer the visitor's actual question first, then add only the most useful next detail. For simple questions, normally answer in 1–3 short sentences. Do not give long biographies or repeat information unless the visitor asks for more detail. Do not sound like a rigid FAQ or repeatedly introduce yourself. Use the conversation history to remember information the visitor already provided and do not ask the same question again unnecessarily. When a visitor describes a business or problem, acknowledge it and ask one useful follow-up question when that would help qualify the lead. When discussing packages, recommend the most appropriate package based on the stated needs rather than listing every package every time. Explain value before pushing for a sale. If the visitor is ready to proceed, guide them toward a consultation or human handoff. If they ask for David, explain who he is briefly and offer the next step. If they ask something outside the information you know, be honest and say David can confirm it rather than inventing an answer.

LEAD QUALIFICATION: Naturally learn the business type, what they want automated, relevant platform, approximate scope and timeline when useful. Do not interrogate the visitor with a long questionnaire. Ask one or two relevant questions at a time. Never request sensitive information unnecessarily. Do not claim that a lead has been saved or emailed unless the website's lead form/handoff flow actually performs that action.

FALLBACKS: If you cannot answer a question confidently, say so professionally and offer to have David follow up. If the visitor wants a human, ask for their name and email only when needed for the handoff. Never invent prices, timelines, capabilities, policies, integrations, testimonials, client results, or personal facts.

IDENTITY EXAMPLES: If asked “Who is David?”, answer briefly: “David Elijah is the founder and lead automation specialist behind Lead Flow Automation. He helps small businesses build AI-powered chatbots and automated systems for lead capture, customer support and follow-up.” You may add a short invitation to schedule a consultation if appropriate, but do not give a long biography. If asked “Who founded Lead Flow Automation?”, answer David Elijah and briefly state his role. If asked “Can I speak to David?”, say yes and guide the visitor toward scheduling a consultation or requesting a human handoff. If asked “What does David do?”, briefly explain that he designs and implements AI chatbot and lead-automation systems for small businesses.

The assistant represents Lead Flow Automation. Keep responses helpful and focused on moving a genuine business conversation forward without being pushy.`;

function cors(origin){const allowed=ALLOWED_ORIGINS.has(origin);return {'Access-Control-Allow-Origin':allowed?origin:DEFAULT_WORKER_ORIGIN,'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Max-Age':'86400','Vary':'Origin'};}
function json(data,status=200,origin=DEFAULT_WORKER_ORIGIN){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...cors(origin)}});}
function clean(value,max=2000){if(value===null||value===undefined)return null;return String(value).trim().slice(0,max);}
function validEmail(value){return /^\S+@\S+\.\S+$/.test(value);}
function conversationId(){return crypto.randomUUID();}
function safeHistory(history){if(!Array.isArray(history))return [];return history.slice(-12).map(m=>({role:m?.role==='assistant'?'assistant':'user',content:clean(m?.content??m?.text,1500)||''})).filter(m=>m.content);}

const INDUSTRY_TAGS={
  'real estate':['office=estate_agent','office=property_management','shop=estate_agent'],
  restaurant:['amenity=restaurant'],restaurants:['amenity=restaurant'],hotel:['tourism=hotel'],
  dentist:['amenity=dentist'],dental:['amenity=dentist'],'law firm':['office=lawyer'],law:['office=lawyer'],
  accounting:['office=accountant'],fitness:['leisure=fitness_centre'],gym:['leisure=fitness_centre'],
  beauty:['shop=beauty','shop=hairdresser'],salon:['shop=hairdresser'],'car dealer':['shop=car'],
  pharmacy:['amenity=pharmacy'],cafe:['amenity=cafe'],school:['amenity=school'],clinic:['amenity=clinic']
};
function buildOverpassQuery(tags,lat,lon,radius){const clauses=tags.map(tag=>{const [key,value]=tag.split('=');return `nwr["${key}"="${value}"](around:${radius},${lat},${lon});`;}).join('');return `[out:json][timeout:55];(${clauses});out center tags;`;}
function normalizeProspects(elements,country){const seen=new Set(),items=[];for(const element of elements||[]){const tags=element.tags||{},name=String(tags.name||'').trim(),lat=element.lat??element.center?.lat,lon=element.lon??element.center?.lon;if(!name||lat==null||lon==null)continue;const key=`${name.toLowerCase()}|${Math.round(Number(lat)*1000)}|${Math.round(Number(lon)*1000)}`;if(seen.has(key))continue;seen.add(key);const website=String(tags.website||tags['contact:website']||'').trim(),phone=String(tags.phone||tags['contact:phone']||'').trim(),email=String(tags.email||tags['contact:email']||'').trim(),address=[tags['addr:housenumber'],tags['addr:street'],tags['addr:city']].filter(Boolean).join(' ');let score=40;if(website)score+=30;if(phone)score+=10;if(email)score+=10;if(tags['addr:street'])score+=5;items.push({name,website,phone,email,address:address||country,latitude:Number(lat),longitude:Number(lon),score:Math.min(95,score),source:'OpenStreetMap',evidence:[website?'Public website listed':'No public website listed',phone?'Public phone listed':'No public phone listed',email?'Public email listed':'No public email listed']});}return items.sort((a,b)=>b.score-a.score);}

async function sendLeadEmail(lead,env){if(!env.RESEND_API_KEY||!env.FROM_EMAIL)return false;const text=[`New LeadFlow consultation request`,``,`Business: ${lead.businessName}`,`Name: ${lead.name}`,`Email: ${lead.email}`,`Phone: ${lead.phone||'Not provided'}`,`Business type: ${lead.businessType}`,`Automation need: ${lead.need}`,`Package interest: ${lead.packageInterest}`,`Timeline: ${lead.timeline}`,`Consent: Yes`,`Consent timestamp: ${lead.consentTimestamp}`,`Conversation ID: ${lead.conversationId}`].join('\n');try{const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.FROM_EMAIL,to:['leadflowautomations.dav@gmail.com'],reply_to:lead.email,subject:`New LeadFlow consultation — ${lead.businessName}`,text})});if(!r.ok)console.error('lead_email_delivery_failed',r.status,await r.text());return r.ok;}catch(error){console.error('lead_email_delivery_error',error);return false;}}
async function chat(request,env,origin){const body=await request.json();const message=clean(body.message,1500);const history=safeHistory(body.history);const id=clean(body.conversationId,100)||conversationId();if(!message)return json({error:'Message is required.'},400,origin);if(!env.AI)return json({error:'AI service is not configured yet.'},503,origin);const prompt=`${BUSINESS_SPEC}\n\nConversation:\n${history.map(m=>`${m.role}: ${m.content}`).join('\n')}\nuser: ${message}\nassistant:`;const result=await env.AI.run(MODEL,{prompt,temperature:0.25,max_tokens:400});const answer=clean(result?.response||result?.text,3000)||'I’m sorry, I could not answer that right now. Please contact David at leadflowautomations.dav@gmail.com.';if(env.DB){await env.DB.prepare('INSERT INTO chat_logs (conversation_id, role, content) VALUES (?, ?, ?)').bind(id,'user',message).run();await env.DB.prepare('INSERT INTO chat_logs (conversation_id, role, content) VALUES (?, ?, ?)').bind(id,'assistant',answer).run();}return json({conversationId:id,answer},200,origin);}
async function createLead(request,env,origin){const b=await request.json();const lead={name:clean(b.name,120),email:clean(b.email,254),phone:clean(b.phone,40),businessName:clean(b.businessName,160),businessType:clean(b.businessType,120),need:clean(b.need,500),packageInterest:clean(b.packageInterest,100),timeline:clean(b.timeline,100),consent:b.consent===true,consentTimestamp:clean(b.consentTimestamp,80),conversationId:clean(b.conversationId,100)||conversationId()};if(!lead.consent)return json({error:'Affirmative consent is required.'},400,origin);if(!lead.name||!validEmail(lead.email)||!lead.businessName||!lead.businessType||!lead.need||!lead.packageInterest||!lead.timeline||!lead.consentTimestamp)return json({error:'Please provide all required lead details.'},400,origin);if(!env.DB)return json({error:'Lead storage is not configured yet.'},503,origin);await env.DB.prepare('INSERT INTO leads (conversation_id,name,email,phone,business_name,business_type,need,package_interest,timeline,consent,consent_timestamp) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(lead.conversationId,lead.name,lead.email,lead.phone,lead.businessName,lead.businessType,lead.need,lead.packageInterest,lead.timeline,1,lead.consentTimestamp).run();const emailSent=await sendLeadEmail(lead,env);return json({ok:emailSent,emailSent,stored:true,conversationId:lead.conversationId},emailSent?201:503,origin);}
async function handoff(request,env,origin){const b=await request.json();const name=clean(b.name,120),email=clean(b.email,254),transcript=clean(b.transcript,12000),reason=clean(b.reason,500)||'Human handoff requested';if(!name||!validEmail(email)||!transcript)return json({error:'Name, email and transcript are required.'},400,origin);let emailSent=false;if(env.RESEND_API_KEY&&env.FROM_EMAIL){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:env.FROM_EMAIL,to:['leadflowautomations.dav@gmail.com'],reply_to:email,subject:`LeadFlow handoff: ${reason}`,text:`Lead: ${name} <${email}>\nReason: ${reason}\n\nTranscript:\n${transcript}`})});emailSent=r.ok;}return json({ok:true,emailSent},200,origin);}
async function health(env,origin){if(!env.DB)return json({ok:false,service:'leadflow-assistant-api',db:false,version:VERSION},503,origin);await env.DB.prepare('SELECT 1').all();await env.DB.prepare('SELECT id FROM leads LIMIT 1').all();await env.DB.prepare('SELECT id FROM chat_logs LIMIT 1').all();return json({ok:true,service:'leadflow-assistant-api',db:true,version:VERSION,emailConfigured:Boolean(env.RESEND_API_KEY&&env.FROM_EMAIL)},200,origin);}

async function prospectSearch(request,env,origin){
  const url=new URL(request.url),location=clean(url.searchParams.get('location'),120),country=clean(url.searchParams.get('country'),120),industry=clean(url.searchParams.get('industry'),120)?.toLowerCase();
  const requested=Number(url.searchParams.get('limit')||100),limit=Math.min(100,Math.max(1,Number.isFinite(requested)?requested:100));
  if(!location||!country||!industry)return json({error:'location, country and industry are required.'},400,origin);
  const tags=INDUSTRY_TAGS[industry]||['office'];
  const geoUrl=`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(`${location}, ${country}`)}`;
  let geoResponse;
  try{geoResponse=await fetch(geoUrl,{headers:{accept:'application/json','user-agent':'LeadFlowAutomation-ProspectResearch/1.0 (+https://leadflowautomations.github.io/)'}});}catch(error){return json({error:'Location provider could not be reached.',detail:String(error?.message||error)},502,origin);}
  if(!geoResponse.ok)return json({error:`Location provider returned HTTP ${geoResponse.status}.`},502,origin);
  const geo=await geoResponse.json();
  if(!Array.isArray(geo)||!geo[0])return json({error:`Could not locate ${location}, ${country}.`},404,origin);
  const lat=Number(geo[0].lat),lon=Number(geo[0].lon),query=buildOverpassQuery(tags,lat,lon,30000);
  const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];let data=null,lastError=null;
  for(const endpoint of endpoints){try{const response=await fetch(`${endpoint}?data=${encodeURIComponent(query)}`,{headers:{accept:'application/json'}});if(!response.ok){lastError=new Error(`HTTP ${response.status}`);continue;}data=await response.json();break;}catch(error){lastError=error;}}
  if(!data)return json({error:'Business search provider unavailable.',detail:String(lastError?.message||lastError||'Unknown error')},502,origin);
  const prospects=normalizeProspects(data.elements,country).slice(0,limit);
  return json({ok:true,query:{location,country,industry},center:{latitude:lat,longitude:lon},count:prospects.length,prospects},200,origin);
}

export default {async fetch(request,env){const origin=request.headers.get('Origin')||DEFAULT_WORKER_ORIGIN;if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});const url=new URL(request.url);try{if(request.method==='GET'&&url.pathname==='/api/health')return await health(env,origin);if(request.method==='GET'&&url.pathname==='/api/prospect-search')return await prospectSearch(request,env,origin);if(request.method==='POST'&&url.pathname==='/api/chat')return await chat(request,env,origin);if(request.method==='POST'&&url.pathname==='/api/leads')return await createLead(request,env,origin);if(request.method==='POST'&&url.pathname==='/api/handoff')return await handoff(request,env,origin);return json({error:'Not found.'},404,origin);}catch(error){console.error('leadflow_worker_error',error);return json({error:'Something went wrong. Please try again.'},500,origin);}},async scheduled(_controller,env){if(env.DB){await env.DB.prepare("DELETE FROM chat_logs WHERE created_at < datetime('now','-90 days')").run();await env.DB.prepare("DELETE FROM leads WHERE created_at < datetime('now','-90 days')").run();}}};
