import engine from './v4.js';

const ORIGIN='https://leadflowautomations.github.io';
const ALLOWED=new Set([ORIGIN,'https://leadflowautomations-github-io.pages.dev']);
const STOP=new Set(['the','and','of','for','a','an','inc','llc','ltd','limited','company','co','corporation','corp','group','real','estate','realty','realtor','brokerage','properties','property','homes','home','agency','services']);
const BAD=['duckduckgo.com','google.com','bing.com','yahoo.com','yelp.com','zillow.com','realtor.com','homes.com','loopnet.com','mapquest.com','yellowpages.com','facebook.com','instagram.com','linkedin.com','tripadvisor.com','opentable.com','wikipedia.org','photon.komoot.io','nominatim.openstreetmap.org','openstreetmap.org'];
function cors(origin){return {'content-type':'application/json; charset=utf-8','cache-control':'no-store','Access-Control-Allow-Origin':ALLOWED.has(origin)?origin:ORIGIN,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Accept','Access-Control-Max-Age':'86400','Vary':'Origin'}};
function url(v){try{const u=new URL(String(v).trim());if(!/^https?:$/.test(u.protocol))return '';u.hash='';return u.href}catch{return ''}}
function domain(v){try{return new URL(v).hostname.replace(/^www\./,'').toLowerCase()}catch{return ''}}
function good(u){const d=domain(u);return !!u&&!!d&&!BAD.some(x=>d===x||d.endsWith('.'+x))}
function tokens(name){return String(name||'').toLowerCase().replace(/&/g,' and ').split(/[^a-z0-9]+/).filter(x=>x.length>2&&!STOP.has(x))}
function guesses(name){const t=tokens(name);const raw=String(name||'').toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9 ]+/g,' ').split(/\s+/).filter(Boolean);const noIndustry=raw.filter(x=>!['real','estate','realty','realtor','brokerage','property','properties','homes','home','agency','services'].includes(x));const vals=[];const add=(s)=>{if(!s)return;const b=s.replace(/[^a-z0-9]/g,'');if(b.length<4)return;const variants=[b,b.replace(/([a-z])([a-z])/g,'$1$2')];const hy=noIndustry.length>1?noIndustry.join('-'):'';if(hy)variants.push(hy);const tokhy=t.length>1?t.join('-'):'';if(tokhy)variants.push(tokhy);for(const base of variants.filter(Boolean)){for(const suffix of ['.com','.net','.org']){for(const prefix of ['https://','https://www.']){const u=prefix+base+suffix;if(!vals.includes(u))vals.push(u)}}}};add(noIndustry.join(''));add(t.join(''));for(const x of t)add(x);add(raw.slice(0,3).join(''));add(raw.slice(0,2).join(''));if(t.length>1)add(t.slice(0,2).join(''));return vals.slice(0,18)}
async function directProbe(candidate){const u=url(candidate);if(!u||!good(u))return '';try{const r=await fetch(u,{redirect:'follow',headers:{accept:'text/html,application/xhtml+xml,text/plain;q=.8','user-agent':'LeadFlowAutomation-WebsiteVerifier/2026.09'}});const ct=(r.headers.get('content-type')||'').toLowerCase();if(r.ok&&(ct.includes('text/html')||ct.includes('application/xhtml+xml')||ct.includes('text/plain')))return good(r.url||u)?(r.url||u):u}catch{}return ''}
async function readerProbe(candidate){const u=url(candidate);if(!u||!good(u))return '';try{const r=await fetch('https://r.jina.ai/'+u,{headers:{accept:'text/plain','user-agent':'LeadFlowAutomation-WebsiteVerifier/2026.09'}});if(r.ok){const text=await r.text();if(text&&text.trim().length>40)return u}}catch{}return ''}
async function probe(candidate){return (await directProbe(candidate))||(await readerProbe(candidate))}
function unwrap(v,base){try{const u=new URL(v,base);for(const k of ['uddg','url','target','dest','destination']){const x=u.searchParams.get(k);if(x)return decodeURIComponent(x)}if(/duckduckgo|bing|yahoo/.test(u.hostname))return '';return u.href}catch{return ''}}
function parseLinks(html,base){const out=[];const add=x=>{const u=url(x);if(good(u)&&!out.some(v=>domain(v)===domain(u)))out.push(u)};for(const m of html.matchAll(/(?:href|data-href)=["']([^"']+)["']/gi))add(unwrap(m[1],base));for(const m of html.matchAll(/uddg=([^&"' >]+)/gi)){try{add(decodeURIComponent(m[1]))}catch{}}return out}
async function search(query,engineName){const host=engineName==='ddg'?'https://html.duckduckgo.com/html/':'https://www.bing.com/search';try{const r=await fetch(host+'?q='+encodeURIComponent(query),{headers:{accept:'text/html','user-agent':'Mozilla/5.0 LeadFlowResearch/2026.09'}});if(!r.ok)return[];return parseLinks(await r.text(),host)}catch{return[]}}
function rank(u,name,location,industry){const d=domain(u),h=(d+' '+u).toLowerCase();if(!good(u))return -999;let s=0;for(const t of tokens(name))if(h.includes(t))s+=18;for(const t of tokens(location))if(h.includes(t))s+=2;if(/real estate|realty|realtor|property|brokerage/i.test(industry)&&/(realty|realestate|properties|property|homes|estate|commercial|commercialre)/i.test(h))s+=3;return s}
async function searchFallback(name,location,industry){const qs=[`"${name}" "${location}" ${industry} official website`,`"${name}" "${location}" website`,`"${name}" ${industry} official`];for(const q of qs){for(const engineName of ['ddg','bing']){const links=await search(q,engineName);const ranked=links.map(u=>({u,s:rank(u,name,location,industry)})).filter(x=>x.s>=18).sort((a,b)=>b.s-a.s);if(ranked[0])return ranked[0].u}}return ''}
async function enrich(p){if(p?.website)return p;for(const g of guesses(p?.name||'')){const found=await probe(g);if(found)return {...p,website:found,websiteDiscovery:'Business-name domain candidate verified'}}const found=await searchFallback(p?.name||'',p?.address||p?.location||'',p?.industry||'');return found?{...p,website:found,websiteDiscovery:'Public web search candidate verified'}:p}
export default {async fetch(request,env,ctx){const origin=request.headers.get('Origin')||ORIGIN;if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(request.method!=='POST')return engine.fetch(request,env,ctx);try{const body=await request.json();const prospects=Array.isArray(body.prospects)?body.prospects:[];const enriched=[];for(const p of prospects)enriched.push(await enrich(p));const headers=new Headers(request.headers);headers.set('Content-Type','application/json');const rewritten=new Request(request,{body:JSON.stringify({...body,prospects:enriched}),headers});const response=await engine.fetch(rewritten,env,ctx);const out=new Headers(response.headers);for(const [k,v] of Object.entries(cors(origin)))out.set(k,v);return new Response(response.body,{status:response.status,statusText:response.statusText,headers:out});}catch(error){return new Response(JSON.stringify({ok:false,error:error?.message||'Prospect research failed'}),{status:500,headers:cors(origin)})}}};