const VERSION='2026-09-05.12';
const ORIGIN='https://leadflowautomations.github.io';
const ALLOWED=new Set([ORIGIN,'https://leadflowautomations-github-io.pages.dev']);
const INDUSTRY_TAGS={
  'real estate':[['office','estate_agent'],['office','property_management'],['shop','estate_agent'],['office','real_estate_agent'],['office','property_agent']],
  restaurant:[['amenity','restaurant']],
  hotel:[['tourism','hotel']],
  dentist:[['amenity','dentist']],
  'law firm':[['office','lawyer']],
  accounting:[['office','accountant']],
  fitness:[['leisure','fitness_centre']],
  beauty:[['shop','beauty'],['shop','hairdresser']],
  'car dealer':[['shop','car']],
  pharmacy:[['amenity','pharmacy']],
  cafe:[['amenity','cafe']],
  school:[['amenity','school']],
  clinic:[['amenity','clinic'],['amenity','doctors']]
};
const INDUSTRY_WORDS={
  'real estate':['real estate','realty','realtor','property','properties','homes','brokerage','estate agent'],
  restaurant:['restaurant','dining','grill','kitchen','bistro'],hotel:['hotel','resort','inn','suites'],dentist:['dentist','dental'],
  'law firm':['law','attorney','legal'],accounting:['accounting','accountant','cpa'],fitness:['fitness','gym','training'],
  beauty:['beauty','salon','spa'],'car dealer':['auto','motor','car','dealer'],pharmacy:['pharmacy','chemist'],cafe:['cafe','coffee'],
  school:['school','academy'],clinic:['clinic','medical','health']
};
const json=(data,status=200,origin=ORIGIN)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','Access-Control-Allow-Origin':ALLOWED.has(origin)?origin:ORIGIN,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Accept','Access-Control-Max-Age':'86400','Vary':'Origin'}});
const clean=(v,n=500)=>v==null?'':String(v).trim().slice(0,n);
const first=(...xs)=>{for(const x of xs){const s=clean(x,1200);if(s)return s}return ''};
const uniq=a=>[...new Set((a||[]).filter(Boolean).map(x=>clean(x,500)))];
const urlOf=v=>{try{const u=new URL(String(v).trim());if(!/^https?:$/.test(u.protocol))return '';u.hash='';return u.href}catch{return ''}};
const validUrl=v=>urlOf(v);
const tokens=s=>clean(s,500).toLowerCase().replace(/&/g,' and ').split(/[^a-z0-9]+/).filter(x=>x.length>2);
async function geocode(location,country){const q=location+', '+country;const u='https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=1&q='+encodeURIComponent(q);try{const r=await fetch(u,{headers:{accept:'application/json','user-agent':'LeadFlowAutomation-Discovery/2026.09'}});if(!r.ok)return null;const a=await r.json();if(!a[0])return null;return{lat:Number(a[0].lat),lon:Number(a[0].lon),display:first(a[0].display_name),countryCode:first(a[0].address?.country_code).toLowerCase(),type:first(a[0].type)}}catch{return null}}
function queryFor(lat,lon,radius,tags){const clauses=tags.map(([k,v])=>`nwr(around:${radius},${lat},${lon})["${k}"="${v}"];`).join('');return`[out:json][timeout:25];(${clauses});out center tags;`}
async function overpass(query){const endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'];for(const endpoint of endpoints){try{const r=await fetch(endpoint+'?data='+encodeURIComponent(query),{headers:{accept:'application/json','user-agent':'LeadFlowAutomation-Discovery/2026.09'}});if(r.ok){const d=await r.json();if(Array.isArray(d.elements))return d.elements}}catch{}}return[]}
async function photon(location,country,industry,lat,lon){const q=encodeURIComponent(industry+' '+location+' '+country);const u=`https://photon.komoot.io/api/?q=${q}&lat=${lat}&lon=${lon}&zoom=12&limit=100`;try{const r=await fetch(u,{headers:{accept:'application/json','user-agent':'LeadFlowAutomation-Discovery/2026.09'}});if(!r.ok)return[];const d=await r.json();return(d.features||[]).map(f=>{const p=f.properties||{},c=f.geometry?.coordinates||[];return{name:first(p.name),address:[p.housenumber,p.street,p.city,p.state,p.postcode].filter(Boolean).join(' '),latitude:Number(c[1]),longitude:Number(c[0]),category:first(p.osm_key,p.osm_value),osmId:p.osm_type&&p.osm_id?String(p.osm_type).toUpperCase()+p.osm_id:'',website:validUrl(first(p.website,p['contact:website'])),phone:first(p.phone,p['contact:phone']),email:first(p.email,p['contact:email']),source:'OpenStreetMap / Photon'}}).filter(x=>x.name&&Number.isFinite(x.latitude)&&Number.isFinite(x.longitude))}catch{return[]}}
function normalizeName(s){return clean(s,500).toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'').trim()}
function normalizeAddress(s){return clean(s,700).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
function fromElement(e,location,industry){const t=e.tags||{},c=e.center||{lat:e.lat,lon:e.lon};const address=[t['addr:housenumber'],t['addr:street'],t['addr:city']||t['addr:place'],t['addr:state'],t['addr:postcode']].filter(Boolean).join(' ');return{name:first(t.name,t['name:en']),address,location,industry,website:validUrl(first(t.website,t['contact:website'],t.url)),phone:first(t.phone,t['contact:phone']),email:first(t.email,t['contact:email']),socials:uniq([t['contact:facebook'],t['contact:instagram'],t['contact:linkedin'],t['contact:twitter']]),latitude:Number(c.lat),longitude:Number(c.lon),osmId:e.type&&e.id?e.type.toUpperCase()+e.id:'',discoveryTags:Object.entries(t).filter(([k])=>['office','shop','amenity','tourism','leisure'].includes(k)).map(([k,v])=>k+'='+v),source:'OpenStreetMap / Overpass'}}
function relevant(p,industry){const words=INDUSTRY_WORDS[industry]||[industry];const h=(p.name+' '+p.discoveryTags.join(' ')).toLowerCase();return words.some(w=>h.includes(w))||p.discoveryTags.length>0}
function dedupe(items){const seen=new Map();for(const p of items){if(!p.name)continue;const key=normalizeName(p.name)+'|'+normalizeAddress(p.address||'')+'|'+(Number.isFinite(p.latitude)?Math.round(p.latitude*1000):'')+'|'+(Number.isFinite(p.longitude)?Math.round(p.longitude*1000):'');if(seen.has(key)){const old=seen.get(key);old.discoverySources=uniq([...(old.discoverySources||[]),p.source]);old.discoveryTags=uniq([...(old.discoveryTags||[]),...(p.discoveryTags||[])]);if(!old.website&&p.website)old.website=p.website;if(!old.phone&&p.phone)old.phone=p.phone;if(!old.email&&p.email)old.email=p.email;continue}seen.set(key,{...p,discoverySources:[p.source]})}return[...seen.values()]}
async function discover(location,country,industry,limit){const g=await geocode(location,country);if(!g)throw new Error('Could not resolve the requested location.');const tags=INDUSTRY_TAGS[industry]||[];if(!tags.length){const p=await photon(location,country,industry,g.lat,g.lon);return{geocode:g,items:dedupe(p.filter(x=>relevant(x,industry))).slice(0,limit)}}const radius=30000;const q=queryFor(g.lat,g.lon,radius,tags);const elements=await overpass(q);let items=elements.map(e=>fromElement(e,location,industry)).filter(p=>p.name&&relevant(p,industry));if(items.length<Math.min(limit,80)){const fallback=await photon(location,country,industry,g.lat,g.lon);items=items.concat(fallback.filter(x=>relevant(x,industry)))}const out=dedupe(items);out.sort((a,b)=>{const av=(a.website?3:0)+(a.phone?2:0)+(a.email?1:0)+(a.address?1:0);const bv=(b.website?3:0)+(b.phone?2:0)+(b.email?1:0)+(b.address?1:0);return bv-av});return{geocode:g,items:out.slice(0,limit)}}
async function handle(request){const u=new URL(request.url),origin=request.headers.get('Origin')||ORIGIN;if(request.method==='OPTIONS')return json({ok:true},204,origin);if(u.pathname==='/api/health')return json({ok:true,version:VERSION,stage:'discover'},200,origin);if(u.pathname==='/api/prospect-search'&&request.method==='GET'){const location=clean(u.searchParams.get('location'),200),country=clean(u.searchParams.get('country'),120),industry=clean(u.searchParams.get('industry'),100).toLowerCase(),limit=Math.min(150,Math.max(20,Number(u.searchParams.get('limit')||150)));if(!location||!country||!industry)return json({ok:false,error:'location, country and industry are required'},400,origin);const d=await discover(location,country,industry,limit);return json({ok:true,version:VERSION,stage:'discover',location,country,industry,requested:limit,totalDiscovered:d.items.length,locationEvidence:d.geocode,prospects:d.items},200,origin)}if(u.pathname==='/api/prospect-discover'&&request.method==='POST'){const body=await request.json().catch(()=>({}));const location=clean(body.location,200),country=clean(body.country,120),industry=clean(body.industry,100).toLowerCase(),limit=Math.min(150,Math.max(20,Number(body.limit||150)));if(!location||!country||!industry)return json({ok:false,error:'location, country and industry are required'},400,origin);const d=await discover(location,country,industry,limit);return json({ok:true,version:VERSION,stage:'discover',location,country,industry,requested:limit,totalDiscovered:d.items.length,locationEvidence:d.geocode,prospects:d.items},200,origin)}return json({ok:false,error:'Not found'},404,origin)}
export default{async fetch(request){try{return await handle(request)}catch(e){return json({ok:false,version:VERSION,stage:'discover',error:e?.message||'Discovery failed'},500,request.headers.get('Origin')||ORIGIN)}}};
